### ISSUE TITLE
jenkins api

### ISSUE THREAD

**Issue by RobinCK** [devlauer/jenkins-keycloak-plugin#4]
How to perform authorization on jenkins api when connecting a plugin

**Comment by devlauer** [comment]
Currently authorization is not supported directly by this plugin. But perhaps you could place your roles in keycloak at realm global level and set full scope allowed like imduffy15 did it: https://github.com/jenkinsci/keycloak-plugin/pull/4 . Or you wait for the next release with the contribution of imduffy15 where you can put your roles in a claims attribute called "roles".

**Comment by RobinCK** [comment]
thanks
